// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Info } from "./Info";
import type { Model } from "./Model";
import type { Theme } from "./Theme";
import type { WebDav } from "./WebDav";

export type Config = { theme: Theme, info: Info, model: Model, webdav: WebDav, };
