// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventMetadata } from "./EventMetadata";
import type { EventType } from "./EventType";
import type { TaskTime } from "./TaskTime";

export type Event = { metadata: EventMetadata, title: string, content: string, event_type: EventType, task_time: TaskTime, finished: boolean, };
