// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventMetadata = { uuid: string, timestamp: bigint, list: number | null, tag: Array<string> | null, };
