// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Priority } from "./Priority";

export type EventField = { "List": number } | { "Tag": Array<string> } | { "Title": string } | { "Content": string } | { "Finished": boolean } | { "Icon": string } | { "Color": string } | { "Priority": Priority } | { "TaskTime": string };
