// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Priority } from "./Priority";

export type FEvent = { id: string, time: string, date: string, listid: string, tag: Array<string> | null, title: string, create: string, finished: boolean, priority: Priority, icon: string, color: string, };
