// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Priority } from "./Priority";

export type FEvent = { id: string, timestamp: bigint, list: number | null, tag: Array<string> | null, title: string, task_time: bigint, finished: boolean, priority: Priority, };
