// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WebDav = { enabled: boolean, host: string, username: string, password: string, remote_dir: string, };
